apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user-api
  type: LoadBalancer
