apiVersion: v1
kind: Service
metadata:
  name: userapi-svc
  labels:
    app: userapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userapi
  type: LoadBalancer
